repo_url: https://github.com/flanksource/karina
repo_name: karina
site_name: karina
theme:
  name: "material"
  palette:
    primary: "royalblue"
  logo: "img/favicon.png"
extra:
  social:
    - type: "github"
      link: "https://github.com/flanksource"
      icon: fontawesome/brands/github-alt
markdown_extensions:
  - admonition
  - fenced_code
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - codehilite:
      linenums: true
nav:
  - User Guide:
      - Overview: ./user-guide/index.md
      - Configuration: ./user-guide/configuration.md
      - Logging In: ./user-guide/login.md
      - Ingress: ./user-guide/ingress.md
      - Logging: ./user-guide/logging.md
      # - Templating: ./user-guide/templating.md
      - Monitoring: ./user-guide/monitoring.md
      - Canary Checks: ./user-guide/canaries.md
      - Databases: ./user-guide/databases.md
      - Dynamic Namespaces: ./user-guide/dynamic-namespaces.md
      - GitOps: ./user-guide/gitops.md
  - Production Runtime:
      - Overview: ./production-runtime/runtime.md
      - Configuration: ./production-runtime/configuration.md
      - Operators:
          - Index: ./production-runtime/operators.md
          - Cert Manager: ./production-runtime/cert-manager.md
          - Databases:
              - Index: ./production-runtime/databases.md
              - Postgres: ./production-runtime/postgres.md
              - Elastic on K8S: ./production-runtime/eck.yml
              - Consul: ./production-runtime//consul.md
          - Sealed Secrets: ./production-runtime/sealed_secrets.md
      - Backup/Restore: ./admin-guide/backup.md
      - Canary Checks: ./production-runtime/canaries.md
      - Dashboards: ./production-runtime/dashboards.md
      - Open Policy Agent: ./production-runtime/opa.md
      - CICD: ./production-runtime/cicd.md
      - Logging: ./production-runtime/logging.md
      - Ingress: ./production-runtime/ingress.md
      - Image Registry (Harbor): ./production-runtime/harbor.md
      - Monitoring: ./production-runtime/monitoring.md
      - Vault: ./production-runtime/vault.md
  - Administrator Guide:
      - Overview: ./admin-guide/index.md
      - Quickstart with vSphere: ./admin-guide/provisioning/vsphere.md
      - Quickstart with Kind: ./admin-guide/provisioning/kind.md
      - Single Sign On: ./admin-guide/sso.md
      - NSX NCP: ./admin-guide/ncp.md
      - CNI: ./admin-guide/cni.md
      - Configuration: ./admin-guide/configuration.md
      - Persistent Volumes: ./admin-guide/persistent-volumes.md
      - Multi-Tenancy: ./admin-guide/index.md
      - Auditing: ./admin-guide/auditing.md
      - Encryption: ./admin-guide/encryption.md
  # - Developer Guide:
  #     - Quickstart: ./developer-guide/index.html#quickstart
  #     - Documentation: ./developer-guide/index.html#documentation
  #     - Common Issues: ./developer-guide/index.html#common-issues
  #     - Mocks/Stubs: ./developer-guide/index.html#common-issues
  #     - Reference: ./developer-guide/make-targets.md
  - Reference:
      - CLI: ./cli/karina.md
      - Configuration: ./reference/config.md
