---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-operator-manager
  namespace: platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: git-operator-leader-election
  namespace: platform-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: git-operator-manager
  namespace: platform-system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: git-operator-manager
rules:
  - apiGroups:
      - git.flanksource.com
    resources:
      - gitbranches
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - git.flanksource.com
    resources:
      - gitbranches/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - git.flanksource.com
    resources:
      - gitopsapis
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - git.flanksource.com
    resources:
      - gitopsapis/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - git.flanksource.com
    resources:
      - gitpullrequests
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - git.flanksource.com
    resources:
      - gitpullrequests/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - git.flanksource.com
    resources:
      - gitrepositories
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - git.flanksource.com
    resources:
      - gitrepositories/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-operator-leader-election
  namespace: platform-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: git-operator-manager
    namespace: platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-operator-manager
  namespace: platform-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-operator-manager
subjects:
  - kind: ServiceAccount
    name: git-operator-manager
    namespace: platform-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: git-operator-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: git-operator-manager
subjects:
  - kind: ServiceAccount
    name: git-operator-manager
    namespace: platform-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: git-operator
  name: git-operator-controller-manager
  namespace: platform-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: git-operator
  template:
    metadata:
      labels:
        control-plane: git-operator
    spec:
      containers:
        - args:
            - --metrics-addr=:8080
            - --enable-leader-election
            - --log-level=debug
          image: docker.io/flanksource/git-operator:{{.gitOperator.version}}
          imagePullPolicy: IfNotPresent
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8888
      serviceAccountName: git-operator-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: platform-system
  labels:
    control-plane: git-operator
  name: git-operator
spec:
  selector:
    control-plane: git-operator
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: git-operator-ing
  namespace: platform-system
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: git-operator-tls
      hosts:
        - git-operator.{{.domain}}
  rules:
    - host: git-operator.{{.domain}}
      http:
        paths:
          - backend:
              serviceName: git-operator
              servicePort: 8888
