---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  - "rbac.authorization.k8s.io"
  resources:
  - deployments
  - services
  - ingresses
  - configmaps
  - roles
  - rolebindings
  - serviceaccounts
  - secrets
  - resourcequotas
  verbs:
  - "*"
