apiVersion: templating.flanksource.com/v1
kind: Template
metadata:
  name: alertmanager-config
spec:
  source:
    apiVersion: monitoring.coreos.com/v1alpha1
    kind: AlertmanagerConfig
    namespaceSelector:
      matchLabels:
        karina.flanksource.com/namespace-name: monitoring
    labelSelector:
      matchLabels:
        alertmanagerConfig: main
  copyToNamespaces:
      {{- if index .monitoring "alertmanager"}}
      {{- if index .monitoring.alertmanager "configNamespaces"}}
      {{- range $ns := .monitoring.alertmanager.configNamespaces }}
    namespaces:
      - {{ $ns }}
      {{- end }}
      {{- else }}
    namespaces: []
      {{- end }}
      {{- else }}
    namespaces: []
      {{- end }}