apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: thanos-sidecar
  namespace: monitoring
spec:
  rules:
  - host: "{{.thanos.thanosSidecarEndpoint}}"
    http:
      paths:
      - backend:
          serviceName: prometheus-operated
          servicePort: 10901
