---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-web-view
  namespace: monitoring
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-web-view
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs: [list, get]
  - nonResourceURLs:
      - '*'
    verbs: [list, get]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-web-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-web-view
subjects:
  - kind: ServiceAccount
    name: kube-web-view
    namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: kube-web-view
  name: kube-web-view
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-web-view
  template:
    metadata:
      labels:
        application: kube-web-view
    spec:
      serviceAccountName: kube-web-view
      containers:
        - name: kube-web-view
          # see https://codeberg.org/hjacobs/kube-web-view/releases
          image: hjacobs/kube-web-view:20.6.0
          args:
            - --port=8080
          # uncomment the following line to enable pod logs
          # (disabled by default as they might consider sensitive information)
          # - "--show-container-logs"
          # uncomment the following line to unhide secret data
          # see also https://kube-web-view.readthedocs.io/en/latest/security.html
          # - "--show-secrets"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 5m
              memory: 100Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: kube-web-view
  name: kube-web-view
  namespace: monitoring
spec:
  selector:
    application: kube-web-view
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    k8s-app: kube-web-view
  name: kube-web-view
  namespace: monitoring
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: kube-web-view.{{.domain}}
      http:
        paths:
          - backend:
              serviceName: kube-web-view
              servicePort: 80
  tls:
    - secretName: kube-web-view-tls
      hosts:
        - kube-web-view.{{.domain}}