apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accountquotas.config.kiosk.sh
spec:
  conversion:
    strategy: None
  group: config.kiosk.sh
  names:
    kind: AccountQuota
    listKind: AccountQuotaList
    plural: accountquotas
    singular: accountquota
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accounts.config.kiosk.sh
spec:
  conversion:
    strategy: None
  group: config.kiosk.sh
  names:
    kind: Account
    listKind: AccountList
    plural: accounts
    singular: account
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templateinstances.config.kiosk.sh
spec:
  conversion:
    strategy: None
  group: config.kiosk.sh
  names:
    kind: TemplateInstance
    listKind: TemplateInstanceList
    plural: templateinstances
    singular: templateinstance
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: templates.config.kiosk.sh
spec:
  conversion:
    strategy: None
  group: config.kiosk.sh
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
