name: Upgrade E2E

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "docs/**"

jobs:
  binary:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:0.6
    steps:
      - uses: actions/checkout@main
      - run: make pack linux
      - uses: actions/upload-artifact@v2
        with:
          name: karina
          path: ./.bin/karina
  test:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), 'skip-e2e')"
    needs: binary
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - v1.18.6
        suite:
          - minimal
        tesults-key:
          - replace
        include:
          - k8s: v1.17.5
            suite: minimal
            tesults-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImFhNDM4ZWYyLTNmMmYtNGNhZS1iYjc2LWI0ZWM4NTMzZDUyZi0xNjExNzM2MzYwMjc5IiwiZXhwIjo0MTAyNDQ0ODAwMDAwLCJ2ZXIiOiIwIiwic2VzIjoiODAzNzI1NTUtNjg1NS00Mjc0LWI1Y2ItMmI5MzY4MGE0OWE2IiwidHlwZSI6InQifQ.wxqfSIHqL8ujffGwMI7HSJXlpiwcZf2uqp8QtWmg7w8
          - k8s: v1.17.5
            suite: minimal-antrea
            tesults-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImFhNDM4ZWYyLTNmMmYtNGNhZS1iYjc2LWI0ZWM4NTMzZDUyZi0xNjExNzUzNTYxMDA4IiwiZXhwIjo0MTAyNDQ0ODAwMDAwLCJ2ZXIiOiIwIiwic2VzIjoiMjU0NzkzMzMtM2NmNy00ZDdhLThjNTgtNTFlMGQ4Mzc5MzI1IiwidHlwZSI6InQifQ.NdxHrZzOaKHRHkzwbKhwNdjUci1TQaaKzwys_xWZSkc
          - k8s: v1.17.5
            suite: monitoring
            #TODO: replace with correct key when it is generated
            tesults-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImFhNDM4ZWYyLTNmMmYtNGNhZS1iYjc2LWI0ZWM4NTMzZDUyZi0xNjExNzUzMzY2MjY4IiwiZXhwIjo0MTAyNDQ0ODAwMDAwLCJ2ZXIiOiIwIiwic2VzIjoiODE2N2MwZmUtYjY4MS00ZWNlLTg4NDgtNDUwNTdhNGY2ZWUxIiwidHlwZSI6InQifQ.ncoWRiX5G6EKj3jh9DPfZ9XC8xNE7HYHinutbSJpdGY
          - k8s: v1.16.9
            suite: minimal
            tesults-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImFhNDM4ZWYyLTNmMmYtNGNhZS1iYjc2LWI0ZWM4NTMzZDUyZi0xNjExNzM0MDQzMzc0IiwiZXhwIjo0MTAyNDQ0ODAwMDAwLCJ2ZXIiOiIwIiwic2VzIjoiNWU5MjBmZjEtMzYxZS00NmVkLTkyNjEtNDk3OTFhNTgxNzdhIiwidHlwZSI6InQifQ.zWRfHeOpiPWTMs_KuhWNKs-Z1CFifgPiQpuk_6nvyNc
          - k8s: v1.16.9
            suite: monitoring
            tesults-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImFhNDM4ZWYyLTNmMmYtNGNhZS1iYjc2LWI0ZWM4NTMzZDUyZi0xNjExNzUzMzg2ODU5IiwiZXhwIjo0MTAyNDQ0ODAwMDAwLCJ2ZXIiOiIwIiwic2VzIjoiMTNjOTk4NDctYjEzMy00ZTk0LTg4NjUtZjQwNTkxYzBlMTFmIiwidHlwZSI6InQifQ.eTr_4v8sT9IhCYqWlGQoH8dy7wE8vZidGffL-mbl-GI
    steps:
      - uses: actions/checkout@main
      - uses: actions/download-artifact@v2
        with:
          name: karina
          path: ./.bin
      - name: Run upgrade testing script
        env:
          GIT_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          SUITE: ${{ matrix.suite }}
          KUBERNETES_VERSION: ${{matrix.k8s}}
          BUILD: test (${{matrix.k8s}}, ${{ matrix.suite }})
          REFERENCE_VERSION: v0.20.4
          TESULTS_TOKEN: ${{ matrix.tesults_key }}
        run: ./test/upgrade.sh
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: test-results-${{matrix.k8s}}-${{matrix.suite}}
          path: test-results/
      - name: Upload snapshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v1
        with:
          name: snapshot-${{matrix.k8s}}-${{matrix.suite}}
          path: artifacts/snapshot.zip
      - name: Generate Kind logs
        if: failure()
        run: |
          mkdir -p artifacts/kind-logs
          .bin/kind export logs --name=upgrade-test artifacts/kind-logs
          tar -cf artifacts/kind-logs/upgrade-${{matrix.suite}}-${{matrix.k8s}}.tar artifacts/kind-logs/*
      - name: Upload Kind logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: upgrade-${{matrix.k8s}}-${{matrix.suite}}.tar
          path: artifacts/kind-logs
